### ISSUE TITLE
Eliminar binarios

### ISSUE THREAD

**Issue by leliel12** [FeD7791/voidFinderProject#4]
hay muchos binarios versionados eliminarlos

**Comment by FeD7791** [comment]
> hay muchos binarios versionados eliminarlos

Ayuda aca: que seria exactamente un binario? elimine files que me resultaran de alguna ejecucion del codigo

**Comment by leliel12** [comment]
Las cosas compiladas no se versionan. "que seria exactamente un binario" es algo que se deberia saber. Chusmear como se configura los gitignore

**Comment by FeD7791** [comment]
Me podrias explicar lo del binario? es lo de los archivos compilados? Si se usar gitignore. No he trabajado con git a este nivel.
